package sk.upjs.ics;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class GUI extends javax.swing.JFrame {

    private Grammar grammar = new Grammar();
    
    public GUI() {
        initComponents();
        
        MouseListener mouseListener = new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    char from = ((String) rulesList.getSelectedValue()).charAt(0);
                    String to = ((String) rulesList.getSelectedValue()).substring(5);
                    AddRuleDialog dialog = new AddRuleDialog(GUI.this, true, grammar, from, to);
                    dialog.setVisible(true);
                    refresh();
                }
            }
        };
        rulesList.addMouseListener(mouseListener);
        
        //rulesList.addListSelectionListener(new ListSelectionListener() {
        //    @Override
        //    public void valueChanged(ListSelectionEvent e) {
        //        char from = ((String) rulesList.getSelectedValue()).charAt(0);
        //        String to = ((String) rulesList.getSelectedValue()).substring(5);
        //        AddRuleDialog dialog = new AddRuleDialog(GUI.this, true, grammar, from, to);
        //        dialog.setVisible(true);
        //        refresh();
        //    }
        //});
        
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRuleButton = new javax.swing.JButton();
        deleteRuleButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rulesList = new javax.swing.JList();
        toIDPDAButton = new javax.swing.JButton();
        selectFileButton = new javax.swing.JButton();
        simulateButton = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        toDFAButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addRuleButton.setText("Add rule");
        addRuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRuleButtonActionPerformed(evt);
            }
        });

        deleteRuleButton.setText("Delete rule");
        deleteRuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRuleButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(rulesList);

        toIDPDAButton.setText("To IDPDA");

        selectFileButton.setText("Select file");

        simulateButton.setText("Simulate");

        fileNameLabel.setText("...");

        toDFAButton.setText("To DFA");
        toDFAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toDFAButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simulateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileNameLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addRuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteRuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toDFAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toIDPDAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectFileButton)
                            .addComponent(simulateButton)
                            .addComponent(fileNameLabel))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addRuleButton)
                        .addComponent(deleteRuleButton)
                        .addComponent(toDFAButton)
                        .addComponent(toIDPDAButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refresh() {
        Map<String, List<String>> rules = grammar.getRules();
        List<String> data = new ArrayList<>();
        for (String key : rules.keySet()) {
            for (String s : rules.get(key)) {
                StringBuilder sb = new StringBuilder();
                sb.append("<html>");
                sb.append("<font color=red>");
                sb.append(key);
                sb.append("</font> -> ");
                boolean inNonterminal = false;
                for (int i = 0; i < s.length(); i++) {
                    if (s.charAt(i) == '♥' && inNonterminal) {  // koniec neterminalu
                        sb.append("</font>");
                        inNonterminal = false;
                    } else if (s.charAt(i) == '♥' && !inNonterminal) {  // zaciatok neterminalu
                        sb.append("<font color=red>");
                        inNonterminal = true;
                    } else {
                        sb.append(s.charAt(i));
                    }
                }
                sb.append("</html>");
                data.add(sb.toString());
            }
        }
        rulesList.setListData(data.toArray());
    }
    
    private void addRuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRuleButtonActionPerformed
        AddRuleDialog addRuleFrame = new AddRuleDialog(this, true, grammar, ' ', null);
        addRuleFrame.setVisible(true);
        refresh();
    }//GEN-LAST:event_addRuleButtonActionPerformed

    private void deleteRuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRuleButtonActionPerformed
        String s = (String) rulesList.getSelectedValue();
        char c = s.charAt(0);
        List<String> list = grammar.getRules().get(c);
        
        String ss = s.substring(5);
        list.remove(ss);
        
        refresh();
    }//GEN-LAST:event_deleteRuleButtonActionPerformed

    private void toDFAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toDFAButtonActionPerformed
        Convertor convertor = new Convertor();
        List<Automaton> automata = convertor.toAutomata(grammar);
        
        StringBuilder sb = new StringBuilder();
        for (Automaton a : automata) {
            sb.append("Automaton " + a.getOwnNonterminal());
            sb.append("\n");
            sb.append(a.toStringHtml());
            sb.append("--------------------------------------");
            sb.append("\n");
        }
        
        DisplayDialog displayDialog = new DisplayDialog(this, true, sb.toString());
        displayDialog.setVisible(true);
    }//GEN-LAST:event_toDFAButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRuleButton;
    private javax.swing.JButton deleteRuleButton;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList rulesList;
    private javax.swing.JButton selectFileButton;
    private javax.swing.JButton simulateButton;
    private javax.swing.JButton toDFAButton;
    private javax.swing.JButton toIDPDAButton;
    // End of variables declaration//GEN-END:variables
}
